In [2]:
docs="""Artificial intelligence is one of the most exciting fields in computer science.
It is changing the way people interact with technology in their daily lives.
Machine learning allows computers to learn patterns from data.
It can make predictions without being explicitly programmed for every individual task.
Deep learning is a branch of machine learning.
It uses neural networks with multiple layers to solve complex problems.
Deep learning can be used for image classification and speech recognition.
It is also useful for natural language processing and recommendation systems.
Recurrent neural networks are designed to work with sequential data.
Traditional RNNs can have difficulty remembering information from long sequences.
This problem is known as the vanishing gradient problem.
Long Short Term Memory networks are commonly known as LSTMs.
LSTMs were introduced to overcome the limitations of traditional RNNs.
They use special memory cells and gates to control information.
The gates decide what information should be remembered or forgotten.
Because LSTMs can remember important information for a longer period of time.
They are useful for many natural language processing applications.
LSTMs can be used for text generation and language modeling.
They can also be used for sentiment analysis and machine translation.
Another important application is next word prediction.
In next word prediction the model receives a sequence of words as input.
The model learns the relationship between different words.
It then predicts which word is most likely to come next.
For example machine learning is a common phrase.
The model can learn that the next word may be powerful.
As the model receives more text during training it learns language patterns.
It gradually learns common sentence structures and word relationships.
This helps the model generate meaningful sequences of text.
An LSTM model can therefore be used to build a simple language model.
The language model can predict the next word based on previous words.
The more useful training data the model receives the better it can learn.
Good training data contains many different sentences and word combinations.
During training the input sentences are converted into numerical representations.
These numerical representations are given to the LSTM network.
The LSTM processes the sequence one word at a time.
It keeps important information in its memory.
Finally the output layer predicts the probability of possible next words.
The word with the highest probability can be selected as the prediction.
This process can be repeated to generate longer sentences.
Therefore LSTMs are useful for learning patterns in sequential text data."""

## the Archecture of of the project  is :
#### Text
  ↓
#### Tokenization
  ↓
##### Token IDs
  ↓
##### Embedding Layer
  ↓
##### LSTM Layer
  ↓
#### Dense Layer
  ↓
#### Softmax
  ↓
#### Next Word

In [3]:
import tensorflow as tf  
from tensorflow.keras.preprocessing.text import Tokenizer

### first we convert the all the text in token one by one.tokennizer means that  we can convrt the sentance into wor by word so the ann doese not know the word dirctecctlty we can convert the numuerical value 

In [4]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts([docs])

## we want to find the the word index

In [5]:
tokenizer.word_index

{'the': 1,
 'can': 2,
 'it': 3,
 'to': 4,
 'for': 5,
 'word': 6,
 'model': 7,
 'is': 8,
 'be': 9,
 'of': 10,
 'and': 11,
 'learning': 12,
 'a': 13,
 'language': 14,
 'are': 15,
 'next': 16,
 'in': 17,
 'data': 18,
 'information': 19,
 'as': 20,
 'lstms': 21,
 'with': 22,
 'machine': 23,
 'used': 24,
 'useful': 25,
 'text': 26,
 'words': 27,
 'training': 28,
 'learn': 29,
 'patterns': 30,
 'networks': 31,
 'this': 32,
 'memory': 33,
 'they': 34,
 'important': 35,
 'prediction': 36,
 'receives': 37,
 'learns': 38,
 'lstm': 39,
 'sentences': 40,
 'one': 41,
 'most': 42,
 'from': 43,
 'deep': 44,
 'neural': 45,
 'also': 46,
 'natural': 47,
 'processing': 48,
 'sequential': 49,
 'traditional': 50,
 'rnns': 51,
 'long': 52,
 'sequences': 53,
 'problem': 54,
 'known': 55,
 'gates': 56,
 'longer': 57,
 'time': 58,
 'many': 59,
 'sequence': 60,
 'input': 61,
 'different': 62,
 'predicts': 63,
 'common': 64,
 'more': 65,
 'during': 66,
 'generate': 67,
 'therefore': 68,
 'numerical': 69,
 'repre

In [6]:
input_sequnce=[]
for sentance in docs.split('\n'): ## to see the all sentance 
    tokanized_sentance=tokenizer.texts_to_sequences([sentance])[0]
    for i in range(1,len(tokanized_sentance)):
        input_sequnce.append(tokanized_sentance[:i+1])
        

In [7]:
input_sequnce

[[72, 73],
 [72, 73, 8],
 [72, 73, 8, 41],
 [72, 73, 8, 41, 10],
 [72, 73, 8, 41, 10, 1],
 [72, 73, 8, 41, 10, 1, 42],
 [72, 73, 8, 41, 10, 1, 42, 74],
 [72, 73, 8, 41, 10, 1, 42, 74, 75],
 [72, 73, 8, 41, 10, 1, 42, 74, 75, 17],
 [72, 73, 8, 41, 10, 1, 42, 74, 75, 17, 76],
 [72, 73, 8, 41, 10, 1, 42, 74, 75, 17, 76, 77],
 [3, 8],
 [3, 8, 78],
 [3, 8, 78, 1],
 [3, 8, 78, 1, 79],
 [3, 8, 78, 1, 79, 80],
 [3, 8, 78, 1, 79, 80, 81],
 [3, 8, 78, 1, 79, 80, 81, 22],
 [3, 8, 78, 1, 79, 80, 81, 22, 82],
 [3, 8, 78, 1, 79, 80, 81, 22, 82, 17],
 [3, 8, 78, 1, 79, 80, 81, 22, 82, 17, 83],
 [3, 8, 78, 1, 79, 80, 81, 22, 82, 17, 83, 84],
 [3, 8, 78, 1, 79, 80, 81, 22, 82, 17, 83, 84, 85],
 [23, 12],
 [23, 12, 86],
 [23, 12, 86, 87],
 [23, 12, 86, 87, 4],
 [23, 12, 86, 87, 4, 29],
 [23, 12, 86, 87, 4, 29, 30],
 [23, 12, 86, 87, 4, 29, 30, 43],
 [23, 12, 86, 87, 4, 29, 30, 43, 18],
 [3, 2],
 [3, 2, 88],
 [3, 2, 88, 89],
 [3, 2, 88, 89, 90],
 [3, 2, 88, 89, 90, 91],
 [3, 2, 88, 89, 90, 91, 92],
 [3, 

In [8]:
max_len=max([len(x) for x in input_sequnce])

In [9]:
max_len

13

In [10]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequance=pad_sequences(input_sequnce,maxlen=max_len,padding='pre')

In [11]:
padded_input_sequance

array([[ 0,  0,  0, ...,  0, 72, 73],
       [ 0,  0,  0, ..., 72, 73,  8],
       [ 0,  0,  0, ..., 73,  8, 41],
       ...,
       [ 0,  0,  0, ..., 30, 17, 49],
       [ 0,  0,  0, ..., 17, 49, 26],
       [ 0,  0, 68, ..., 49, 26, 18]], dtype=int32)

In [12]:
X=padded_input_sequance[:,:-1]

In [13]:
X

array([[ 0,  0,  0, ...,  0,  0, 72],
       [ 0,  0,  0, ...,  0, 72, 73],
       [ 0,  0,  0, ..., 72, 73,  8],
       ...,
       [ 0,  0,  0, ..., 12, 30, 17],
       [ 0,  0,  0, ..., 30, 17, 49],
       [ 0,  0, 68, ..., 17, 49, 26]], dtype=int32)

In [14]:
Y=padded_input_sequance[:,-1]

In [15]:
Y

array([ 73,   8,  41,  10,   1,  42,  74,  75,  17,  76,  77,   8,  78,
         1,  79,  80,  81,  22,  82,  17,  83,  84,  85,  12,  86,  87,
         4,  29,  30,  43,  18,   2,  88,  89,  90,  91,  92,  93,   5,
        94,  95,  96,  12,   8,  13,  97,  10,  23,  12,  98,  45,  31,
        22,  99, 100,   4, 101, 102, 103,  12,   2,   9,  24,   5, 104,
       105,  11, 106, 107,   8,  46,  25,   5,  47,  14,  48,  11, 108,
       109,  45,  31,  15, 111,   4, 112,  22,  49,  18,  51,   2, 113,
       114, 115,  19,  43,  52,  53,  54,   8,  55,  20,   1, 116, 117,
        54, 118, 119,  33,  31,  15, 120,  55,  20,  21, 121, 122,   4,
       123,   1, 124,  10,  50,  51, 125, 126,  33, 127,  11,  56,   4,
       128,  19,  56, 129, 130,  19, 131,   9, 132, 133, 134,  21,   2,
       136,  35,  19,   5,  13,  57, 137,  10,  58,  15,  25,   5,  59,
        47,  14,  48, 138,   2,   9,  24,   5,  26, 139,  11,  14, 140,
         2,  46,   9,  24,   5, 141, 142,  11,  23, 143,  35, 14

In [16]:
X.shape

(373, 12)

In [17]:
Y.shape

(373,)

In [18]:
from tensorflow.keras.utils import to_categorical

In [19]:
Y=to_categorical(Y,num_classes=191)
Y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
Y.shape
X = X.astype('int32')
Y = Y.astype('float32')

In [21]:
from tensorflow.keras.models import Sequential
from keras.layers import Embedding,LSTM,Dense
model=Sequential()

In [22]:
model.add(Embedding(191,77,input_length=12))
model.add(LSTM(150))
model.add(Dense(191,activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
I0000 00:00:1789195522.917695      58 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13756 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0000 00:00:1789195522.920950      58 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13756 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:00:05.0, compute capability: 7.5


In [23]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [24]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.fit(X,Y,epochs=100)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4933 - loss: 2.2941
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5040 - loss: 2.2111
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5657 - loss: 2.1206
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5576 - loss: 2.0277
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5845 - loss: 1.9368
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6193 - loss: 1.8688
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6381 - loss: 1.7873
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6783 - loss: 1.7136
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6890 - loss: 1.6454
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7131 - loss: 1.5763
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7239 - loss: 1.5130
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy:

In [26]:
X.shape

(373, 12)

In [27]:
Y.shape

(373, 191)

In [29]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

def predict_next_word(sentence):
    # Sentence ko token IDs mein convert karo
    token_list = tokenizer.texts_to_sequences([sentence])[0]

    # Last 12 words/tokens rakho
    token_list = token_list[-12:]

    # Agar 12 se kam hain to padding
    token_list = pad_sequences(
        [token_list],
        maxlen=12,
        padding='pre'
    )

    # Prediction
    predicted = model.predict(token_list, verbose=0)

    # Highest probability wala word
    predicted_id = np.argmax(predicted, axis=-1)[0]

    # ID ko word mein convert karo
    for word, index in tokenizer.word_index.items():
        if index == predicted_id:
            return word

    return "Unknown"

In [30]:
sentence = "artificial intelligence is"
next_word = predict_next_word(sentence)

print("Input:", sentence)
print("Predicted next word:", next_word)

Input: artificial intelligence is
Predicted next word: one


In [32]:
sentence = "artificial intelligence"

for i in range(10):
    next_word = predict_next_word(sentence)
    sentence += " " + next_word

print(sentence)

artificial intelligence is one of the most exciting fields in computer science
